# Generated by Django 3.2 on 2022-07-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='post title')),
                ('summary', models.CharField(max_length=400)),
                ('content', models.TextField(verbose_name='post content')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
    ]
