# Generated by Django 3.2 on 2022-07-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='', verbose_name='post thumbnail'),
            preserve_default=False,
        ),
    ]
